[programs.localnet]
idling = "EstAWeDWJtzCpkvx5SyeykQFoyaQ5hDBAb57a8fhpVef"
idle_plants = "5Xooq9NawThiYdisrAgc6oyPkesS4VbGM6YTw66pVXPj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/amazzeo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
