[programs.localnet]
idling = "3gTqaTAKfq6h41XDSFb2iUZt8bXFKTpbU3nsxbBzipcN"
idle_plants = "4H8FuFgabDNba1S8KPLjcni2zBGV2GK8DeffDwtU535f"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./keypairs/testkey.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
